# Generated by Django 5.0.1 on 2026-03-23 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('instructor', models.CharField(max_length=150)),
                ('capacity', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('schedule_day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('schedule_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gym Classes',
                'ordering': ['schedule_day', 'schedule_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show')], default='confirmed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_bookings', to='members.member')),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classes.gymclass')),
            ],
            options={
                'ordering': ['-booking_date', '-created_at'],
                'unique_together': {('gym_class', 'member', 'booking_date')},
            },
        ),
    ]
